const data = [
  {
    id: 1,
    category: "backend",
    title: "WJ Smoothie, node, mongoDB, express with JWT authentication",
    desc: "A simple yet fantastic project when learning more about backend as well as front and back communication.",
    demo: "https://mern-hcun.onrender.com",
    github: "https://github.com/William0209/MERN",
  },
  {
    id: 2,
    category: "frontend",
    title: "Furniture Website (Frontend)",
    desc: "A furniture website built using HTML, CSS, and JavaScript. It has a clean and minimal but responsive design with smooth animations.",
    demo: "https://william0209.github.io/furniture1/",
    github: "https://github.com/William0209/furniture1",
  },
  {
    id: 3,
    category: "frontend",
    title: "Portfolio website (Frontend)",
    desc: "Simple and responsive portfolio website using HTML, CSS, and JavaScript.",
    demo: "https://william0209.github.io/front-portf/",
    github: "https://github.com/William0209/front-portf",
  },
  {
    id: 4,
    category: "frontend",
    title: "Interior Designer Wenbsite (Frontend)",
    desc: "A responsive interior website built using HTML, CSS, and JavaScript. It has a clean and minimal design with smooth animations.",
    demo: "https://william0209.github.io/InteriorDesign-FRONT/",
    github: "https://github.com/William0209/InteriorDesign-FRONT",
  },
  {
    id: 5,
    category: "frontend",
    title: "Coffee Shop Website (Frontend)",
    desc: "Vibrant and responsive coffee shop website built using HTML, CSS, and JavaScript.",
    demo: "https://william0209.github.io/coffee-FRONT/",
    github: "https://github.com/William0209/coffee-FRONT",
  },
  {
    id: 6,
    category: "backend",
    title: "Soon deploying my first big MERN STACK project",
    desc: "Tourguide website, keep an eye out for it! Feel free to checkout the repo on github.",
    demo: "#",
    github: "https://github.com/William0209/EXP",
  },
  {
    id: 7,
    category: "frontend",
    title: "Anime website",
    desc: " First next.js project, which i built alongside a crashcourse including next 14 and TS. Feel free to checkout the repo on github.",
    demo: "https://wjanime.netlify.app/",
    github: "https://github.com/William0209/anime_project",
  },
];

// {
//   id: 4,
//   category: "uiux",
//   title: "Project Title Four (UIUX)",
//   desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!",
//   demo: "#",
//   github: "#",
// },
// {
//   id: 5,
//   category: "uiux",
//   title: "Project Title Five (UIUX)",
//   desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut! ",
//   demo: "#",
//   github: "#",
// },
export default data;
